import { Talent } from '../types';

export const talents: Talent[] = [
    {
      id: '1',
      name: 'Sarah Jenkins',
      title: 'Senior UX Designer',
      rating: 4.9,
      reviews: 124,
      hourlyRate: 85,
      category: 'Digital & Tech',
      skills: ['Figma', 'Prototyping', 'User Research', 'Design Systems', 'Wireframing'],
      image: 'https://picsum.photos/id/64/200/200',
      verified: true,
      location: 'San Francisco, CA',
      bio: 'I am a passionate UX Designer with over 7 years of experience crafting digital products for startups and enterprise clients. My focus is on creating intuitive, accessible, and delightful user experiences. I have worked with FinTech, HealthTech, and EdTech companies to solve complex product challenges.',
      responseTime: '1 hour',
      languages: ['English (Native)', 'Spanish (Conversational)'],
      completedProjects: 142,
      portfolio: [
        { id: 'p1', title: 'FinTech Dashboard Redesign', image: 'https://picsum.photos/id/1/600/400', category: 'UI Design' },
        { id: 'p2', title: 'Healthcare Mobile App', image: 'https://picsum.photos/id/119/600/400', category: 'Mobile' },
        { id: 'p3', title: 'E-commerce Design System', image: 'https://picsum.photos/id/20/600/400', category: 'System' },
        { id: 'p4', title: 'Travel Booking Flow', image: 'https://picsum.photos/id/24/600/400', category: 'UX Research' },
      ],
      reviewsList: [
        { id: 'r1', user: 'Mark D.', rating: 5, date: '2 weeks ago', comment: 'Sarah was incredible to work with. She understood our complex requirements immediately and delivered high-quality designs.' },
        { id: 'r2', user: 'Alice W.', rating: 5, date: '1 month ago', comment: 'Top tier designer. Very communicative and professional throughout the entire project.' }
      ]
    },
    {
      id: '2',
      name: 'David Chen',
      title: 'Full Stack Developer',
      rating: 5.0,
      reviews: 89,
      hourlyRate: 110,
      category: 'Digital & Tech',
      skills: ['React', 'Node.js', 'TypeScript', 'Next.js', 'PostgreSQL'],
      image: 'https://picsum.photos/id/91/200/200',
      verified: true,
      location: 'Toronto, Canada',
      bio: 'Full Stack Developer specializing in high-performance web applications. I build scalable, secure, and maintainable code for modern SaaS platforms. I have a strong background in both frontend architecture and backend system design.',
      responseTime: '2 hours',
      languages: ['English (Native)', 'Mandarin (Fluent)'],
      completedProjects: 78,
      portfolio: [
        { id: 'p1', title: 'SaaS Analytics Platform', image: 'https://picsum.photos/id/60/600/400', category: 'Web App' },
        { id: 'p2', title: 'Real-time Chat Application', image: 'https://picsum.photos/id/48/600/400', category: 'Full Stack' }
      ],
      reviewsList: [
        { id: 'r1', user: 'TechCorp Inc.', rating: 5, date: '3 days ago', comment: 'David writes exceptional code. Delivered ahead of schedule.' }
      ]
    },
    {
      id: '3',
      name: 'Elena Rodriguez',
      title: 'Brand Strategist',
      rating: 4.8,
      reviews: 56,
      hourlyRate: 95,
      category: 'Marketing & Growth',
      skills: ['SEO', 'Content Strategy', 'Branding', 'Social Media', 'Copywriting'],
      image: 'https://picsum.photos/id/42/200/200',
      verified: false,
      location: 'Barcelona, Spain',
      bio: 'Helping brands find their voice and grow their audience. I combine data-driven insights with creative storytelling to build compelling brand narratives.',
      responseTime: '4 hours',
      languages: ['English (Fluent)', 'Spanish (Native)'],
      completedProjects: 56,
      portfolio: [
        { id: 'p1', title: 'Fashion Brand Launch', image: 'https://picsum.photos/id/325/600/400', category: 'Branding' }
      ],
      reviewsList: []
    },
    {
      id: '4',
      name: 'Marcus Johnson',
      title: 'Technical Writer',
      rating: 4.7,
      reviews: 34,
      hourlyRate: 60,
      category: 'Creative & Media',
      skills: ['API Documentation', 'Copywriting', 'Technical Guides', 'Whitepapers'],
      image: 'https://picsum.photos/id/55/200/200',
      verified: true,
      location: 'Austin, TX',
      bio: 'I translate complex technical concepts into clear, concise documentation for developers and end-users.',
      responseTime: '5 hours',
      languages: ['English (Native)'],
      completedProjects: 45
    },
    {
      id: '5',
      name: 'Priya Patel',
      title: 'Frontend Engineer',
      rating: 4.9,
      reviews: 210,
      hourlyRate: 125,
      category: 'Digital & Tech',
      skills: ['Vue.js', 'Tailwind', 'Performance', 'Accessibility', 'Testing'],
      image: 'https://picsum.photos/id/33/200/200',
      verified: true,
      location: 'London, UK',
      bio: 'Frontend specialist obsessed with pixel perfection and web performance. I create silky smooth user interfaces.',
      responseTime: '30 mins',
      languages: ['English (Native)', 'Hindi (Fluent)'],
      completedProjects: 200
    },
    {
      id: '6',
      name: 'Tom Wilson',
      title: 'Business Consultant',
      rating: 4.6,
      reviews: 15,
      hourlyRate: 150,
      category: 'Marketing & Growth',
      skills: ['Startup Growth', 'Financial Modeling', 'Pitch Decks'],
      image: 'https://picsum.photos/id/77/200/200',
      verified: false,
      location: 'New York, NY',
      bio: 'Ex-McKinsey consultant helping startups scale from Series A to B.',
      responseTime: '1 day',
      languages: ['English (Native)'],
      completedProjects: 12
    },
    {
      id: '7',
      name: 'Emily Rose',
      title: 'Ceramic Artist',
      rating: 5.0,
      reviews: 42,
      hourlyRate: 45,
      category: 'Crafts & Handmade',
      skills: ['Pottery', 'Clay Art', 'Sculpture', 'Glazing'],
      image: 'https://picsum.photos/id/12/200/200',
      verified: true,
      location: 'Portland, OR',
      bio: 'Handcrafted ceramics for the modern home. I specialize in functional wheel-thrown pottery.',
      responseTime: '3 hours',
      languages: ['English (Native)'],
      completedProjects: 88
    },
    {
      id: '8',
      name: 'Jack Miller',
      title: 'Voice Actor',
      rating: 4.8,
      reviews: 90,
      hourlyRate: 70,
      category: 'Performance',
      skills: ['Voice-over', 'Audio Editing', 'Acting', 'Narration'],
      image: 'https://picsum.photos/id/66/200/200',
      verified: true,
      location: 'Los Angeles, CA',
      bio: 'Versatile voice actor with a home studio. Ready for commercials, audiobooks, and animation.',
      responseTime: '1 hour',
      languages: ['English (Native)'],
      completedProjects: 150
    }
  ];
